<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Frontend Store</title>';
echo '<link rel="stylesheet" href="css/normalize.css">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com">';
echo '<link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">';
echo '<link rel="stylesheet" href="css/styles.css">';
echo '</head>';
echo '<body>';
echo '<header class="header">';
echo '<a href="index.html">';
echo '<img class="header__logo" src="img/logo.png" alt="Logo FrontEnd Store">';
echo '</a>';
echo '</header>';
echo '';
echo '<nav class="navegacion">';
echo '<a class="navegacion__enlace navegacion__enlace--activo" href="index.html">Tienda</a>';
echo '<a class="navegacion__enlace" href="nosotros.html">Nosotros</a>';
echo '</nav>';
echo '';
echo '<main class="contenedor">';
echo '<h1>Nuestros productos</h1>';
echo '<div class="grid">';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/1.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">VueJS</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/2.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">AngularJS</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/3.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">ReactJS</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/4.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">Redux</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/5.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">NodeJS</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/6.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">SASS</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/7.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">HTML5</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/8.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">GitHub</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/9.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">Bulma</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/10.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">TypeScript</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/11.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">Drupal</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/12.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">JavaScript</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/13.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">GraphQL</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="producto">';
echo '<a href="producto.html">';
echo '<img class="producto__imagen" src="img/14.jpg" alt="VueJS">';
echo '<div class="producto__info">';
echo '<p class="producto__nombre">Wordpress</p>';
echo '<p class="producto__precio">$25</p>';
echo '</div>';
echo '</a>';
echo '</div><!-- Producto -->';
echo '';
echo '<div class="grafico grafico--camisas">';
echo '';
echo '</div>';
echo '';
echo '<div class="grafico grafico--node">';
echo '';
echo '</div>';
echo '</div>';
echo '</main>';
echo '';
echo '<footer class="footer">';
echo '<p class="footer__texto">Front End Store - Todos los derechos reservados 2021.</p>';
echo '</footer>';
echo '</body>';
echo '</html>';
?>